{% set name = "fsm-lite" %}
{% set version = "v1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nvalimak/{{ name|lower }}/archive/{{ version }}-stable.tar.gz
  sha256: f781a9fbab5265bd09b3b5b7e1cba904582ec201c3d30baed36e28a03de3ac61

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - sdsl-lite
  run:
    - sdsl-lite

test:
  commands:
    - fsm-lite -h 2>&1 | grep whitespace-separated

about:
  home: https://github.com/nvalimak/fsm-lite
  license: GPL-3
  license_family: GPL
  summary: 'Frequency-based String Mining (lite)'
  description: |
    A single-core implemetation of frequency-based substring mining. Used to
    count k-mers in populations of genomes (supplied as fasta files).
  dev_url: https://github.com/nvalimak/fsm-lite
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - johnlees

