package:
  name: batvi
  version: "1.04"

source:
  url: https://www.comp.nus.edu.sg/~bioinfo/batvi/batvi1.03.tar.gz
  path: src

requirements:
  run:
    - samtools
    - blast
    - bedtools
    - picard
    - bwa
    - zlib

  host:
    - zlib

  build:
    - {{ compiler('c') }}

about:
  home: https://www.comp.nus.edu.sg/~bioinfo/batvi/
  license: GPLv3+
  summary: Detect viral integrations 
  
