package:
  name: batvi
  version: "1.04"

source:
  url: https://www.comp.nus.edu.sg/~bioinfo/batvi/batvi1.03.tar.gz
  path: src
  sha256: 5768322d5e320484cfd57dbe469d5863f55fae3123a462037f12cb934b65f2ed

requirements:
  run:
    - samtools
    - blast
    - bedtools
    - picard
    - bwa
    - zlib

  host:
    - zlib

  build:
    - {{ compiler('c') }}

build:
  number: 1
  string: cond
about:
  home: https://www.comp.nus.edu.sg/~bioinfo/batvi/
  license: GPLv3+
  summary: Detect viral integrations 
  
test:
  commands:
    - echo "Run test data on the website.. "
