{% set version = "1.0.0" %}

package:
  name: htstream
  version: {{ version }}

source:
  url: https://github.com/ibest/HTStream/archive/v{{ version }}-release.tar.gz
  md5: b86484dbfa1541cff22125647a5f6e92

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost
    - boost-cpp
    - libboost
  run:
    - libboost

test:
  commands:
    - hts_Stats --help

about:
  home: https://ibest.github.io/HTStream/
  license: Apache 2.0
  license_file: LICENSE
  summary: |
    HTStream is a fast, quality control pipeline for Hight Throughput Sequencing data.
    The difference between HTStream and other pipelines is that HTStreams uses a tab delimited fastq format which allows for streaming from application to application.
    This streaming creates some awesome efficiencies when processing HTS data.
